import { Sintoma, SintomaId } from '@/types/dengue';

export const CATALOGO_SINTOMAS: Sintoma[] = [
  // ── CATEGORÍA GENERAL (#1 - #10) ──
  {
    id: 'S01',
    nombre: 'Fiebre (≥38°C)',
    descripcion: 'Tengo fiebre alta o siento mucho calor en el cuerpo',
    icono: 'thermometer',
    categoria: 'GENERAL',
    peso: 3,
    esSignoAlarma: false,
  },
  {
    id: 'S02',
    nombre: 'Dolor de cabeza',
    descripcion: 'Me duele la cabeza intensamente en la frente o sienes',
    icono: 'brain',
    categoria: 'GENERAL',
    peso: 2,
    esSignoAlarma: false,
  },
  {
    id: 'S03',
    nombre: 'Dolor detrás de los ojos',
    descripcion: 'Siento dolor o presión profunda detrás de las cuencas de los ojos',
    icono: 'eye',
    categoria: 'GENERAL',
    peso: 2,
    esSignoAlarma: false,
  },
  {
    id: 'S04',
    nombre: 'Dolor muscular',
    descripcion: 'Me duelen los músculos del cuerpo (brazos, piernas, espalda)',
    icono: 'dumbbell',
    categoria: 'GENERAL',
    peso: 2,
    esSignoAlarma: false,
  },
  {
    id: 'S05',
    nombre: 'Dolor en articulaciones',
    descripcion: 'Me duelen las coyunturas (rodillas, codos, muñecas)',
    icono: 'bone',
    categoria: 'GENERAL',
    peso: 2,
    esSignoAlarma: false,
  },
  {
    id: 'S06',
    nombre: 'Náuseas',
    descripcion: 'Siento náuseas, estómago revuelto o ganas de vomitar',
    icono: 'activity',
    categoria: 'GENERAL',
    peso: 1,
    esSignoAlarma: false,
  },
  {
    id: 'S07',
    nombre: 'Vómitos ocasionales',
    descripcion: 'He vomitado 1 o 2 veces en el día',
    icono: 'alert-circle',
    categoria: 'GENERAL',
    peso: 2,
    esSignoAlarma: false,
  },
  {
    id: 'S08',
    nombre: 'Sarpullido / Manchas',
    descripcion: 'Tengo erupciones rojas, picazón o sarpullido en la piel',
    icono: 'sparkles',
    categoria: 'GENERAL',
    peso: 2,
    esSignoAlarma: false,
  },
  {
    id: 'S09',
    nombre: 'Cansancio extremo',
    descripcion: 'Siento gran debilidad, agotamiento o falta de energía',
    icono: 'battery-low',
    categoria: 'GENERAL',
    peso: 1,
    esSignoAlarma: false,
  },
  {
    id: 'S10',
    nombre: 'Falta de apetito',
    descripcion: 'No me da hambre, he perdido el gusto por la comida',
    icono: 'utensils-crossed',
    categoria: 'GENERAL',
    peso: 1,
    esSignoAlarma: false,
  },

  // ── CATEGORÍA WARNING — Signos de ALARMA (#11 - #20) ──
  {
    id: 'S11',
    nombre: 'Dolor abdominal intenso',
    descripcion: 'Tengo un dolor muy fuerte y constante en la barriga',
    icono: 'flame',
    categoria: 'WARNING',
    peso: 8,
    esSignoAlarma: true,
  },
  {
    id: 'S12',
    nombre: 'Vómitos persistentes',
    descripcion: 'He vomitado 3 o más veces seguidas y no retengo líquidos',
    icono: 'alert-triangle',
    categoria: 'WARNING',
    peso: 7,
    esSignoAlarma: true,
  },
  {
    id: 'S13',
    nombre: 'Sangrado de encías',
    descripcion: 'Me sangran las encías al cepillarme o espontáneamente',
    icono: 'droplet',
    categoria: 'WARNING',
    peso: 8,
    esSignoAlarma: true,
  },
  {
    id: 'S14',
    nombre: 'Sangrado nasal',
    descripcion: 'Me ha salido sangre de la nariz sin haberme golpeado',
    icono: 'droplet',
    categoria: 'WARNING',
    peso: 8,
    esSignoAlarma: true,
  },
  {
    id: 'S15',
    nombre: 'Sangrado vaginal inusual',
    descripcion: 'Tengo sangrado menstrual fuera de mi ciclo o muy abundante',
    icono: 'droplet',
    categoria: 'WARNING',
    peso: 8,
    esSignoAlarma: true,
  },
  {
    id: 'S16',
    nombre: 'Sangre en orina o heces',
    descripcion: 'He notado orina rojiza o heces oscuras/negras',
    icono: 'test-tube',
    categoria: 'WARNING',
    peso: 9,
    esSignoAlarma: true,
  },
  {
    id: 'S17',
    nombre: 'Somnolencia / Letargia',
    descripcion: 'Siento demasiado sueño, me cuesta mantener los ojos abiertos',
    icono: 'moon',
    categoria: 'WARNING',
    peso: 7,
    esSignoAlarma: true,
  },
  {
    id: 'S18',
    nombre: 'Inquietud o irritabilidad',
    descripcion: 'Me siento extremadamente desesperado/a, agitado/a o inquieto/a',
    icono: 'zap',
    categoria: 'WARNING',
    peso: 7,
    esSignoAlarma: true,
  },
  {
    id: 'S19',
    nombre: 'Piel fría o pegajosa',
    descripcion: 'Siento la piel fría al tacto, húmeda o sudoración fría',
    icono: 'snowflake',
    categoria: 'WARNING',
    peso: 8,
    esSignoAlarma: true,
  },
  {
    id: 'S20',
    nombre: 'Hinchazón en el cuerpo',
    descripcion: 'Noto hinchazón marcada en la cara, manos, pies o vientre',
    icono: 'maximize-2',
    categoria: 'WARNING',
    peso: 7,
    esSignoAlarma: true,
  },

  // ── CATEGORÍA SEVERE — Signos de DENGUE GRAVE (#21 - #25) ──
  {
    id: 'S21',
    nombre: 'Dificultad para respirar',
    descripcion: 'Me cuesta respirar, me falta el aire o siento que me ahogo',
    icono: 'wind',
    categoria: 'SEVERE',
    peso: 10,
    esSignoAlarma: true,
  },
  {
    id: 'S22',
    nombre: 'Sangrado abundante / Vomitar sangre',
    descripcion: 'He vomitado sangre fresca o con motas oscuras',
    icono: 'syringe',
    categoria: 'SEVERE',
    peso: 10,
    esSignoAlarma: true,
  },
  {
    id: 'S23',
    nombre: 'Confusión o desorientación',
    descripcion: 'Siento confusión mental, no sé bien qué día es o dónde estoy',
    icono: 'help-circle',
    categoria: 'SEVERE',
    peso: 10,
    esSignoAlarma: true,
  },
  {
    id: 'S24',
    nombre: 'Desmayo o desvanecimiento',
    descripcion: 'Me he desmayado, he perdido la consciencia o me desvanecí',
    icono: 'zap-off',
    categoria: 'SEVERE',
    peso: 10,
    esSignoAlarma: true,
  },
  {
    id: 'S25',
    nombre: 'Pulso muy débil o desbocado',
    descripcion: 'Siento palpitaciones muy rápidas o latidos casi imperceptibles',
    icono: 'heart-pulse',
    categoria: 'SEVERE',
    peso: 10,
    esSignoAlarma: true,
  },
];

export function obtenerSintomaPorId(id: SintomaId): Sintoma | undefined {
  return CATALOGO_SINTOMAS.find((s) => s.id === id);
}

export function obtenerSintomasPorCategoria(categoria: Sintoma['categoria']): Sintoma[] {
  return CATALOGO_SINTOMAS.filter((s) => s.categoria === categoria);
}
